# Generated by Django 5.0 on 2023-12-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('numero_personas', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
    ]
