# Generated by Django 5.0 on 2023-12-16 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatos1', '0003_reservacion_correo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='correo_usuario',
        ),
    ]
